services:
  postgres:
    image: postgres:latest
    privileged: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: file_share
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"